name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    name: Create Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.Changelog.outputs.changelog }}
          draft: true
          prerelease: false
  publish:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn --prefer-offline --no-progress --non-interactive --frozen-lockfile
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
    name: Create Changelog
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false